import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import JsonLd from "@/components/JsonLd";
import ChatWidget from "@/components/iisf/ChatWidget";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const SITE_NAME = "International Intersectional Safety Foundation";
const SITE_URL = "https://intersectionalsafety.org";
const DEFAULT_DESCRIPTION =
  "Guardians of the Algorithm — IISF stewards the Charter of Fundamental Intersectional Safety Rights and the Grandin, Heumann, and Crenshaw Standards for sensory safety, kinetic equity, and algorithmic accountability.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),

  title: {
    default: SITE_NAME,
    template: `%s | ${SITE_NAME}`,
  },
  description: DEFAULT_DESCRIPTION,

  applicationName: SITE_NAME,
  keywords: [
    "intersectional safety",
    "algorithmic accountability",
    "sensory safety",
    "kinetic equity",
    "disability rights",
    "robotics safety",
    "sidewalk delivery robots",
    "Grandin Standard",
    "Heumann Standard",
    "Crenshaw Standard",
    "IISF",
    "human rights technology",
    "AI ethics",
    "accessible infrastructure",
    "501c3 nonprofit",
  ],
  authors: [{ name: SITE_NAME, url: SITE_URL }],
  creator: SITE_NAME,
  publisher: SITE_NAME,

  icons: {
    icon: [
      { url: "/iisf-logo.png", type: "image/png", sizes: "512x512" },
    ],
    apple: [{ url: "/iisf-logo.png" }],
  },

  formatDetection: { telephone: false },

  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: SITE_NAME,
    description: DEFAULT_DESCRIPTION,
    // OG images auto-generated by opengraph-image.tsx per route
  },

  twitter: {
    card: "summary_large_image",
    title: SITE_NAME,
    description: DEFAULT_DESCRIPTION,
    // Twitter images auto-generated by twitter-image.tsx per route
  },

  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  alternates: {
    canonical: SITE_URL,
    types: {
      "application/rss+xml": `${SITE_URL}/rss.xml`,
    },
  },

  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION ?? undefined,
    other: {
      "msvalidate.01":
        process.env.NEXT_PUBLIC_BING_SITE_VERIFICATION ?? "",
      "yandex-verification":
        process.env.NEXT_PUBLIC_YANDEX_VERIFICATION ?? "",
    },
  },
};

const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": "NonprofitOrganization",
  name: "International Intersectional Safety Foundation",
  alternateName: "IISF",
  url: SITE_URL,
  logo: `${SITE_URL}/iisf-logo.png`,
  description: DEFAULT_DESCRIPTION,
  foundingDate: "2024",
  sameAs: [
    "https://www.linkedin.com/company/intersectional-safety-foundation",
    "https://github.com/Vector4g",
    "https://vectorforgood.com",
  ],
  contactPoint: {
    "@type": "ContactPoint",
    contactType: "research partnerships",
    url: `${SITE_URL}/#contact`,
  },
};

const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: SITE_NAME,
  url: SITE_URL,
  publisher: {
    "@type": "NonprofitOrganization",
    name: SITE_NAME,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#05060a] text-slate-100`}
      >
        <JsonLd data={organizationJsonLd} />
        <JsonLd data={websiteJsonLd} />
        {children}
        <ChatWidget />
      </body>
    </html>
  );
}
